version: "3"
services:
  redis:
    image: redis
    container_name: redis-docker
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
      - ./server/redis.conf:/usr/local/etc/redis/redis.conf
      - ./server/redis-rep.conf:/usr/local/etc/redis/redis-rep.conf
